#This line is like importing tools from a toolbox. It's bringing in special helpers called List and Tuple from Python's typing section.
from typing import List, Tuple # a Tuple is immuatable

#recipe's chosen from Gordan Ramsay's Ultimate Cookery Course https://www.gordonramsay.com/gr/recipes/brietoastwithberries/

#each 'Tuple' is a recipe that contains several variables that creates the "object"
#Tuple[
#name of the recipe, 
#list of ingredients, 
#serving size,
#cooking time,
#cooking complexity (how many steps),
#what type of meal  (breakfast, lunch, dinner, dessert),
#event to cook this meal for]
recipe_db: List[Tuple[str, List[str], int, int, int, str, str]] = [
    (
        "melted brie toast with macerated berries",
        ["3 cups mixed berries, divided", 
         "1/4th cup (50g) sugar",
         "Zest of 1/2th Lemon",
         "1 tablespoon lemon juice"
         ],
         2,
         120,
         3,
         "Breakfast",
         "No Event"
    ),
    (
        "texas hanger steak tacos with pico de gallo",
        ["1 hanger steak",
         "kosher salt",
         "black pepper",
         "olive oil",
         "1 cleaned cactus pad(napal)",
         "1 diced small red onion",
         "1 lime",
         "1 frescno chile sliced",
         "3 scallions sliced thick, discarded roots",
         "1 bunch cilantro, roughly chopped",
         "1 diced tomato",
         "1 clove garlic",
         "1 avocado, sliced thick",
         "4 corn tortillas",
         "mexican crema or sour cream"
         ],
         1,
         30,
         8,
         "Lunch",
         "No Event"
    ),
    (
        "fresh prawn rolls",
        ["200g dried vermicelli or fine rice noodles",
         "500g cooked king prawns, peeled, deveined and roughly chopped",
         "2 baby gem lettuces, shredded",
         "4 spring onions, trimmed and chopped",
         "2 large carrots, peeled and grated",
         "4 tbsp chopped coriander",
         "4 tbsp chopped Thai basil",
         "4 tbsp chopped mint",
         "Juice of 2 limes",
         "26 round rice paper sheets (16cm diameter)"
         ],
         5,
         30,
         5,
         "Lunch",
         "No Event"
     ),
     (
         "beef wellington",
         ["2 x 400g beef fillets",
          "Olive oil, for frying",
          "500g mixture of wild mushrooms, cleaned",
          "1 thyme sprig, leaves only",
          "500g puff pastry",
          "8 slices of Parma ham",
          "2 egg yolks, beaten with 1 tbsp water and a pinch of salt",
          "Sea salt and freshly ground black pepper",
          "200g beef trimmings (ask the butcher to reserve these when trimming the fillet)",
          "4 large shallots, peeled and sliced",
          "12 black peppercorns",
          "1 bay leaf",
          "1 thyme sprig",
          "Splash of red wine vinegar",
          "1 x 750ml bottle red wine",
          "750ml beef stock"
         ],
         4,
         120,
         11,
         "Dinner",
         "No Event"
     ),
     (
         "potato and butternut squash gratin with crispy shallots",
         ["3 shallots, peeled",
          "2 cups neutral oil such as canola",
          "Kosher salt",
          "1 ½ pounds butternut squash, neck only, ideally less than 3” diameter",
          "1 ½ pounds large waxy potatoes, such as red, about 3 medium potatoes",
          "16 oz (2 cups) whole milk",
          "16 oz (2 cups) heavy cream",
          "4 large garlic cloves, smashed",
          "2 sprigs thyme",
          "2 bay leaves",
          "4 ounces gruyere cheese, finely grated",
          "1 tablespoon kosher salt",
          "A few cracks of freshly ground black pepper",
          "Butter, for greasing"
         ],
         7,
         120,
         11,
         "Dinner",
         "Christmas"
     ),
     (
        "Holiday Lemon-Herb Chicken Thighs With A Crispy Bacon Gravy",
        [
            "8 each bone-in chicken thighs (about 3-4 pounds)", 
            "Flaky sea salt",
             "fresh cracked pepper",
            "Olive oil",
            "2-3 tablespoons all-purpose flour",
            "pinch of chili flakes",
            "1 lemon, zested",
            "4 slices, thick cut bacon, sliced into 1/2 inch pieces",
            "1/2 cup diced yellow onion",
            "2 garlic cloves, chopped",
            "1-12 ounce bottle of dry hard cider",
            "2 cups warm chicken stock, divided",
            "2 lemons, divided",
            "3-4 sprigs of fresh thyme",
            "2 sprigs of fresh rosemary",
        ],
        6, 
        45,
        4,
        "Dinner",
        "Thanksgiving"
     ),
     (
        "Individual Sticky Toffee Puddings",
        [
            "5 ounces dates, pits removed, roughly chopped (about ¾ cup)", 
            "1/2 teaspoon baking soda",
            "1/4 cup boiling water",
            "3 tablespoons unslated butter, room temperature",
            "6 tablespoons light brown sugar",
            "1 egg",
            "1/2 cup + 2 tablespoons all purpose flour",
            "1/2 teaspoon baking powder",
            "1/2 cup unsalted butter",
            "1 cup packed brown sugar",
            "2 tablespoons milk",
            "2 tablespoobs heavy cream",
            "2 tablespoons corn syrup",
            "Tiny pinch kosher salt",
            "2 tablespoons bourbon",
            "freshly whipped cream"
        ],
        6,
        45,
        6,
        "Dessert",
        "Christmas"
      ),
      (
        "Maine Lobster BLT from Ramsay Around The World",
        [
            "1/2 cup unsalted butter, room temperture",
            "2 tablespoons edible seaweed, rehydrated and chopped",
            "2 tablespoons tarragon leaves, finely chopped",
            "zest of 1 lemon",
            "1 teaspoon minced garlic",
            "1 teaspoon smoked paprika",
            "1/4 teaspoon salt",
            "4 sliced extra thick-cut bacon",
            "kosher salt",
            "freshly craked black pepper",
            "unsalted butter",
            "2 eggs",
            "smoked paprika",
            "1 whole lobster, blacked and meat removed in-tact",
            "1/2 avacado, pit removed",
            "1 yellow onion, sliced into 1/2-inc rounds",
            "2 slicced artisanal bread",
            "1 tablespoon mayonnaise",
            "2 tablespoons fresh or rehydrated wakae seaweed, squeezed dry then finely chopped",
            "1 lemon, for zesting",
            "1 large heriloom tomato, sliced into 1/2-inch rounds",
            "baby gem, lettuce leaves"
        ],
        1,
        30, 
        14,
        "Lunch",
        "No event"
      ),
      (
          "Gordon's Simple Marinara at Home",
          [
              "2 28 Oz Cans of Peeled San Marazano Tomatoes", 
              "1 Large Yellow Onion, Julienned ",
              "6 Garlic Gloves, Sliced Thin",
              "6 Basil Leafs, Torn ",
              "2 Tablespoons Tomato Paste",
              "1 Cup Red Wine",
              "1/8 Cup Olive Oil",
              "Salt & Pepper"
          ],
          4,
          90,
          12,
          "Lunch",
          "No event"
      ),
      (
          "Steak with Chimichurri and Potatoes",
          [
              "Sirloin Steak",
              "Olive Oil", 
              "10 Potaoes thinly sliced",
              "6 Whole Mushrooms",
              "4-5 Small Vine Ripe Tomatoes",
              "3-4 Spring Onions Chopped",
              "1 1/2 Garlic Cloves",
              "1 Red Onion, Thinly sliced",
              "Handful of Parsley",
              "Salt",
              "Pepper",
              "Butter",
              "1 1/2 Cloves of Garlic",
              "handful of Mint",
              "handful of Basil",
              "handful of Parsley",
              "1 Chili, sliced",
              "2 Tablespoons of Olive Oil",
              "1 Tablespoon Red Wine Vinegar",
              "1 Tablespoon of Honey",
              "Lemon Zest"
          ],
          2,
          30,
          10,
          "Dinner",
          "No event"
      )
]